# Generated by Django 4.1.4 on 2023-02-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todolist",
            old_name="item",
            new_name="name",
        ),
    ]
