# Generated by Django 4.1.4 on 2023-02-10 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0002_rename_item_todolist_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="completed",
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("complete", models.BooleanField()),
                (
                    "toDoList",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ToDoApp.todolist",
                    ),
                ),
            ],
        ),
    ]
