# Generated by Django 4.1.4 on 2023-02-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0003_remove_todolist_completed_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
