# Generated by Django 4.1.4 on 2023-02-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0004_alter_item_complete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="complete",
            new_name="completed",
        ),
    ]
