# Generated by Django 4.1.4 on 2023-02-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0005_rename_complete_item_completed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="completed",
            new_name="complete",
        ),
    ]
